role_index:
    path:     /
    defaults: { _controller: "AdminBundle:SekolikoRole:index" }
    methods:  GET

role_new:
    path:     /new
    defaults: { _controller: "AdminBundle:SekolikoRole:new" }
    methods:  [GET, POST]

role_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:SekolikoRole:edit" }
    methods:  [GET, POST]

role_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:SekolikoRole:update" }
    methods:  [POST, PUT]

role_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:SekolikoRole:delete" }
    methods:  [GET, DELETE]

role_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:SekolikoRole:deleteGroup" }
    methods:  POST